// FeatureGrid — bordered grid of features.
function FeatureGrid() {
  const items = [
    {
      n: '01',
      title: 'Shared containers, isolated projects',
      body: 'One MySQL serves every checkout. Each project gets its own database, user, and credentials — created on first start, reused forever.',
      code: '$ dev start\n✓ mysql:8.0  already running (shared)\n✓ Database "my-project" created',
    },
    {
      n: '02',
      title: 'Dedicated when you need it',
      body: 'Add dedicated: true to any service and it runs as a private container for that project — fully isolated from the shared pool.',
      code: 'services:\n  - image: elasticsearch\n    tag: 8.11\n    dedicated: true',
    },
    {
      n: '03',
      title: 'Smart stop · reference counted',
      body: 'dev stop only shuts a shared container down when no other active project depends on it. No accidental kills.',
      code: '~ mysql:8.0   kept running\n             (in use by: api-project)',
    },
    {
      n: '04',
      title: '.env generated, never overwritten',
      body: 'env: true writes connection strings on start. Variables you added by hand are preserved in a separate section.',
      code: '# Generated by dev\nDB_PORT=3380\n# User-defined\nAPP_KEY=base64:…',
    },
    {
      n: '05',
      title: 'Deterministic ports',
      body: 'Each image:tag gets a stable host port derived from the canonical port and the version. mysql:8.0 → 3380. mysql:5.7 → 3357. They never collide.',
      code: 'mysql:8.0     → 3380\nmysql:5.7     → 3357\nelastic:8.11  → 9281',
    },
    {
      n: '06',
      title: 'Any image, not just the supported list',
      body: 'Unsupported images run shared like anything else. dev.env prompts once per project before starting them.',
      code: '! meilisearch:v1.7 is not\n  a supported service.\n  Acknowledge? [y/N]',
    },
  ];
  return (
    <section style={{ paddingTop: 96, paddingBottom: 96, borderTop: '1px solid var(--border-1)' }}>
      <div className="container">
        <Eyebrow>/ 02 — features</Eyebrow>
        <h2 style={{ fontFamily: 'var(--font-sans)', fontWeight: 600, fontSize: 40, lineHeight: 1.1, letterSpacing: '-0.015em', color: 'var(--fg-1)', margin: '12px 0 48px', maxWidth: 720 }}>
          Six rules that make one binary worth installing.
        </h2>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(320px, 1fr))', gap: 0, border: '1px solid var(--border-1)', borderRadius: 6, overflow: 'hidden' }}>
          {items.map((it, i) => (
            <div key={i} style={{ borderRight: '1px solid var(--border-1)', borderBottom: '1px solid var(--border-1)', padding: 28, background: 'var(--bg-1)' }}>
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 14 }}>
                <span style={{ fontFamily: 'var(--font-mono)', fontSize: 12, color: 'var(--fg-3)', letterSpacing: '0.06em' }}>/ {it.n}</span>
                <span style={{ width: 8, height: 8, background: 'var(--color-lime)' }}></span>
              </div>
              <h3 style={{ fontFamily: 'var(--font-sans)', fontWeight: 600, fontSize: 20, lineHeight: 1.25, color: 'var(--fg-1)', margin: '0 0 8px' }}>{it.title}</h3>
              <p style={{ fontSize: 14, lineHeight: 1.55, color: 'var(--fg-2)', margin: '0 0 16px' }}>{it.body}</p>
              <pre style={{ margin: 0, padding: 12, background: 'var(--bg-3)', border: '1px solid var(--border-1)', borderRadius: 4, fontFamily: 'var(--font-mono)', fontSize: 12, lineHeight: 1.55, color: 'var(--fg-1)', overflowX: 'auto' }}>{it.code}</pre>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

Object.assign(window, { FeatureGrid });
